# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class EndpointReadyState(str, Enum):
    """
    Enum for the ready state of an endpoint.
    """

    """
    allowed enum values
    """
    UNKNOWN = 'UNKNOWN'
    READY = 'READY'
    NOT_READY = 'NOT_READY'
    NOT_FOUND = 'NOT_FOUND'
    FOUND_MULTIPLE = 'FOUND_MULTIPLE'
    CONDITION_NOT_FOUND = 'CONDITION_NOT_FOUND'
    INGRESS_RULE_NOT_FOUND = 'INGRESS_RULE_NOT_FOUND'
    INGRESS_NOT_CONFIGURED = 'INGRESS_NOT_CONFIGURED'
    CONTAINER_MISSING = 'CONTAINER_MISSING'
    PROGRESS_DEADLINE_EXCEEDED = 'PROGRESS_DEADLINE_EXCEEDED'
    REVISION_MISSING = 'REVISION_MISSING'
    COMPLETE = 'COMPLETE'
    FAILED_JOB = 'FAILED_JOB'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EndpointReadyState from a JSON string"""
        return cls(json.loads(json_str))


