# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.external_dns import ExternalDns

class TestExternalDns(unittest.TestCase):
    """ExternalDns unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalDns:
        """Test ExternalDns
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalDns`
        """
        model = ExternalDns()
        if include_optional:
            return ExternalDns(
                enabled = True,
                values = platform_api_python_client.models.external_dns_overrides.ExternalDnsOverrides()
            )
        else:
            return ExternalDns(
        )
        """

    def testExternalDns(self):
        """Test ExternalDns"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
