# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.cluster_components import ClusterComponents

class TestClusterComponents(unittest.TestCase):
    """ClusterComponents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterComponents:
        """Test ClusterComponents
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterComponents`
        """
        model = ClusterComponents()
        if include_optional:
            return ClusterComponents(
                kube_prometheus_stack = platform_api_python_client.models.kube_prometheus_stack.KubePrometheusStack(
                    enabled = True, 
                    values = platform_api_python_client.models.kube_prometheus_stack_overrides.KubePrometheusStackOverrides(), ),
                istio = platform_api_python_client.models.istio.Istio(
                    enabled = True, 
                    values = platform_api_python_client.models.istio_overrides.IstioOverrides(
                        istio_cni = platform_api_python_client.models.istio_cni_subchart_overrides.IstioCniSubchartOverrides(
                            cni = platform_api_python_client.models.istio_cni_overrides.IstioCniOverrides(
                                cni_bin_dir = '', 
                                cni_conf_dir = '', ), ), ), ),
                cert_manager = platform_api_python_client.models.cert_manager.CertManager(
                    enabled = True, 
                    values = platform_api_python_client.models.cert_manager_overrides.CertManagerOverrides(), ),
                ingress_nginx = platform_api_python_client.models.ingress_nginx.IngressNginx(
                    enabled = True, 
                    values = platform_api_python_client.models.ingress_nginx_overrides.IngressNginxOverrides(), ),
                spire_crds = platform_api_python_client.models.spire_crds.SpireCrds(
                    enabled = True, 
                    values = platform_api_python_client.models.spire_crds_overrides.SpireCrdsOverrides(), ),
                spire = platform_api_python_client.models.spire.Spire(
                    enabled = True, 
                    values = platform_api_python_client.models.spire_overrides.SpireOverrides(), ),
                external_dns = platform_api_python_client.models.external_dns.ExternalDns(
                    enabled = True, 
                    values = platform_api_python_client.models.external_dns_overrides.ExternalDnsOverrides(), ),
                prometheus_adapter = platform_api_python_client.models.prometheus_adapter.PrometheusAdapter(
                    enabled = True, 
                    values = platform_api_python_client.models.prometheus_adapter_overrides.PrometheusAdapterOverrides(), ),
                keda = platform_api_python_client.models.keda.Keda(
                    enabled = True, 
                    values = platform_api_python_client.models.keda_overrides.KedaOverrides(), ),
                fluent_bit = platform_api_python_client.models.fluent_bit.FluentBit(
                    enabled = True, 
                    values = platform_api_python_client.models.fluent_bit_overrides.FluentBitOverrides(), ),
                argo_rollouts = platform_api_python_client.models.argo_rollouts.ArgoRollouts(
                    enabled = True, 
                    values = platform_api_python_client.models.argo_rollouts_overrides.ArgoRolloutsOverrides(), ),
                network_operator = platform_api_python_client.models.network_operator.NetworkOperator(
                    enabled = True, 
                    values = platform_api_python_client.models.network_operator_overrides.NetworkOperatorOverrides(), ),
                opentelemetry_collector = platform_api_python_client.models.opentelemetry_collector.OpentelemetryCollector(
                    enabled = True, 
                    values = platform_api_python_client.models.opentelemetry_collector_overrides.OpentelemetryCollectorOverrides(), ),
                gpu_operator = platform_api_python_client.models.gpu_operator.GpuOperator(
                    enabled = True, 
                    values = platform_api_python_client.models.gpu_operator_overrides.GpuOperatorOverrides(), ),
                longhorn = platform_api_python_client.models.longhorn.Longhorn(
                    enabled = True, 
                    values = platform_api_python_client.models.longhorn_overrides.LonghornOverrides(), ),
                metrics_server = platform_api_python_client.models.metrics_server.MetricsServer(
                    enabled = True, 
                    values = platform_api_python_client.models.metrics_server_overrides.MetricsServerOverrides(), ),
                teleport_kube_agent = platform_api_python_client.models.teleport_kube_agent.TeleportKubeAgent(
                    enabled = True, 
                    values = platform_api_python_client.models.teleport_kube_agent_overrides.TeleportKubeAgentOverrides(), ),
                final_stack = platform_api_python_client.models.final_stack.FinalStack(
                    enabled = True, 
                    values = platform_api_python_client.models.final_stack_overrides.FinalStackOverrides(), )
            )
        else:
            return ClusterComponents(
        )
        """

    def testClusterComponents(self):
        """Test ClusterComponents"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
