# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.vault_scope import VaultScope

class TestVaultScope(unittest.TestCase):
    """VaultScope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVaultScope(self):
        """Test VaultScope"""
        # inst = VaultScope()

if __name__ == '__main__':
    unittest.main()
