# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.cluster_registration_request import ClusterRegistrationRequest

class TestClusterRegistrationRequest(unittest.TestCase):
    """ClusterRegistrationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterRegistrationRequest:
        """Test ClusterRegistrationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterRegistrationRequest`
        """
        model = ClusterRegistrationRequest()
        if include_optional:
            return ClusterRegistrationRequest(
                display_name = '',
                storage_class = '',
                region = '',
                cloud_provider = 'gcp',
                credential = platform_api_python_client.models.cluster_credential.ClusterCredential(
                    server = '', 
                    bearer_token = '', 
                    ca_cert = '', )
            )
        else:
            return ClusterRegistrationRequest(
                display_name = '',
                storage_class = '',
                credential = platform_api_python_client.models.cluster_credential.ClusterCredential(
                    server = '', 
                    bearer_token = '', 
                    ca_cert = '', ),
        )
        """

    def testClusterRegistrationRequest(self):
        """Test ClusterRegistrationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
