# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.create_service_account_response import CreateServiceAccountResponse

class TestCreateServiceAccountResponse(unittest.TestCase):
    """CreateServiceAccountResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateServiceAccountResponse:
        """Test CreateServiceAccountResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateServiceAccountResponse`
        """
        model = CreateServiceAccountResponse()
        if include_optional:
            return CreateServiceAccountResponse(
                workos_id = '',
                name = '',
                description = '',
                scopes = [
                    ''
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                client_secret = ''
            )
        else:
            return CreateServiceAccountResponse(
                workos_id = '',
                client_secret = '',
        )
        """

    def testCreateServiceAccountResponse(self):
        """Test CreateServiceAccountResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
