# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.create_dynamo_deployment_request import CreateDynamoDeploymentRequest

class TestCreateDynamoDeploymentRequest(unittest.TestCase):
    """CreateDynamoDeploymentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateDynamoDeploymentRequest:
        """Test CreateDynamoDeploymentRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateDynamoDeploymentRequest`
        """
        model = CreateDynamoDeploymentRequest()
        if include_optional:
            return CreateDynamoDeploymentRequest(
                max_surge = 56,
                max_unavailable = 56,
                name = 'ar1c2v7s6djuy1zmetozkhdomha1b0',
                cluster_id = 56,
                hardware_instance_id = 56,
                user_annotations = {
                    'key' : ''
                    },
                chart_revision = '',
                model = '',
                served_model_name = '',
                min_replicas = 56,
                max_replicas = 56,
                concurrency = 56,
                cooldown_period = 56,
                extra_args = '',
                hf_token = '',
                env_vars = {
                    'key' : ''
                    },
                endpoint_bearer_token = '',
                endpoint_certificate_authority = '',
                enable_logging = True,
                enable_node_model_cache = True,
                backend_protocol = 'HTTP'
            )
        else:
            return CreateDynamoDeploymentRequest(
                name = 'ar1c2v7s6djuy1zmetozkhdomha1b0',
                cluster_id = 56,
                hardware_instance_id = 56,
                model = '',
        )
        """

    def testCreateDynamoDeploymentRequest(self):
        """Test CreateDynamoDeploymentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
