# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_client.api.external_api import EXTERNALApi


class TestEXTERNALApi(unittest.TestCase):
    """EXTERNALApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EXTERNALApi()

    def tearDown(self) -> None:
        pass

    def test_create_compute_deployment_deployments_compute_post(self) -> None:
        """Test case for create_compute_deployment_deployments_compute_post

        Create Compute Deployment
        """
        pass

    def test_create_inference_deployment_deployments_inference_post(self) -> None:
        """Test case for create_inference_deployment_deployments_inference_post

        Create Inference Deployment
        """
        pass

    def test_create_payment_payments_post(self) -> None:
        """Test case for create_payment_payments_post

        Create Payment
        """
        pass

    def test_create_payment_setup_payments_setup_post(self) -> None:
        """Test case for create_payment_setup_payments_setup_post

        Create Payment Setup
        """
        pass

    def test_create_training_deployment_deployments_training_post(self) -> None:
        """Test case for create_training_deployment_deployments_training_post

        Create Training Deployment
        """
        pass

    def test_delete_payment_method_payments_methods_payment_method_delete(self) -> None:
        """Test case for delete_payment_method_payments_methods_payment_method_delete

        Delete Payment Method
        """
        pass

    def test_get_compute_deployment_deployments_compute_deployment_id_get(self) -> None:
        """Test case for get_compute_deployment_deployments_compute_deployment_id_get

        Get Compute Deployment
        """
        pass

    def test_get_credits_credits_get(self) -> None:
        """Test case for get_credits_credits_get

        Get Credits
        """
        pass

    def test_get_deployment_status_deployments_status_deployment_id_get(self) -> None:
        """Test case for get_deployment_status_deployments_status_deployment_id_get

        Get Deployment Status
        """
        pass

    def test_get_deployments_deployments_get(self) -> None:
        """Test case for get_deployments_deployments_get

        Get Deployments
        """
        pass

    def test_get_hardware_instances_hardware_instances_get(self) -> None:
        """Test case for get_hardware_instances_hardware_instances_get

        Get Hardware Instances
        """
        pass

    def test_get_inference_deployment_deployments_inference_deployment_id_get(self) -> None:
        """Test case for get_inference_deployment_deployments_inference_deployment_id_get

        Get Inference Deployment
        """
        pass

    def test_get_payment_methods_payments_methods_get(self) -> None:
        """Test case for get_payment_methods_payments_methods_get

        Get Payment Methods
        """
        pass

    def test_get_prebuilt_images_prebuilt_images_get(self) -> None:
        """Test case for get_prebuilt_images_prebuilt_images_get

        Get Prebuilt Images
        """
        pass

    def test_get_training_deployment_deployments_training_deployment_id_get(self) -> None:
        """Test case for get_training_deployment_deployments_training_deployment_id_get

        Get Training Deployment
        """
        pass

    def test_update_deployment_status_deployments_status_deployment_id_put(self) -> None:
        """Test case for update_deployment_status_deployments_status_deployment_id_put

        Update Deployment Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
