# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.cluster_config import ClusterConfig

class TestClusterConfig(unittest.TestCase):
    """ClusterConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterConfig:
        """Test ClusterConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterConfig`
        """
        model = ClusterConfig()
        if include_optional:
            return ClusterConfig(
                components = platform_api_python_client.models.cluster_components.ClusterComponents(
                    kube_prometheus_stack = platform_api_python_client.models.kube_prometheus_stack.KubePrometheusStack(
                        enabled = True, 
                        values = platform_api_python_client.models.kube_prometheus_stack_overrides.KubePrometheusStackOverrides(), ), 
                    istio = platform_api_python_client.models.istio.Istio(
                        enabled = True, ), 
                    cert_manager = platform_api_python_client.models.cert_manager.CertManager(
                        enabled = True, ), 
                    ingress_nginx = platform_api_python_client.models.ingress_nginx.IngressNginx(
                        enabled = True, ), 
                    spire_crds = platform_api_python_client.models.spire_crds.SpireCrds(
                        enabled = True, ), 
                    spire = platform_api_python_client.models.spire.Spire(
                        enabled = True, ), 
                    external_dns = platform_api_python_client.models.external_dns.ExternalDns(
                        enabled = True, ), 
                    prometheus_adapter = platform_api_python_client.models.prometheus_adapter.PrometheusAdapter(
                        enabled = True, ), 
                    keda = platform_api_python_client.models.keda.Keda(
                        enabled = True, ), 
                    fluent_bit = platform_api_python_client.models.fluent_bit.FluentBit(
                        enabled = True, ), 
                    argo_rollouts = platform_api_python_client.models.argo_rollouts.ArgoRollouts(
                        enabled = True, ), 
                    network_operator = platform_api_python_client.models.network_operator.NetworkOperator(
                        enabled = True, ), 
                    opentelemetry_collector = platform_api_python_client.models.opentelemetry_collector.OpentelemetryCollector(
                        enabled = True, ), 
                    gpu_operator = platform_api_python_client.models.gpu_operator.GpuOperator(
                        enabled = True, ), 
                    longhorn = platform_api_python_client.models.longhorn.Longhorn(
                        enabled = True, ), 
                    metrics_server = platform_api_python_client.models.metrics_server.MetricsServer(
                        enabled = True, ), 
                    teleport_kube_agent = platform_api_python_client.models.teleport_kube_agent.TeleportKubeAgent(
                        enabled = True, ), 
                    final_stack = platform_api_python_client.models.final_stack.FinalStack(
                        enabled = True, ), )
            )
        else:
            return ClusterConfig(
                components = platform_api_python_client.models.cluster_components.ClusterComponents(
                    kube_prometheus_stack = platform_api_python_client.models.kube_prometheus_stack.KubePrometheusStack(
                        enabled = True, 
                        values = platform_api_python_client.models.kube_prometheus_stack_overrides.KubePrometheusStackOverrides(), ), 
                    istio = platform_api_python_client.models.istio.Istio(
                        enabled = True, ), 
                    cert_manager = platform_api_python_client.models.cert_manager.CertManager(
                        enabled = True, ), 
                    ingress_nginx = platform_api_python_client.models.ingress_nginx.IngressNginx(
                        enabled = True, ), 
                    spire_crds = platform_api_python_client.models.spire_crds.SpireCrds(
                        enabled = True, ), 
                    spire = platform_api_python_client.models.spire.Spire(
                        enabled = True, ), 
                    external_dns = platform_api_python_client.models.external_dns.ExternalDns(
                        enabled = True, ), 
                    prometheus_adapter = platform_api_python_client.models.prometheus_adapter.PrometheusAdapter(
                        enabled = True, ), 
                    keda = platform_api_python_client.models.keda.Keda(
                        enabled = True, ), 
                    fluent_bit = platform_api_python_client.models.fluent_bit.FluentBit(
                        enabled = True, ), 
                    argo_rollouts = platform_api_python_client.models.argo_rollouts.ArgoRollouts(
                        enabled = True, ), 
                    network_operator = platform_api_python_client.models.network_operator.NetworkOperator(
                        enabled = True, ), 
                    opentelemetry_collector = platform_api_python_client.models.opentelemetry_collector.OpentelemetryCollector(
                        enabled = True, ), 
                    gpu_operator = platform_api_python_client.models.gpu_operator.GpuOperator(
                        enabled = True, ), 
                    longhorn = platform_api_python_client.models.longhorn.Longhorn(
                        enabled = True, ), 
                    metrics_server = platform_api_python_client.models.metrics_server.MetricsServer(
                        enabled = True, ), 
                    teleport_kube_agent = platform_api_python_client.models.teleport_kube_agent.TeleportKubeAgent(
                        enabled = True, ), 
                    final_stack = platform_api_python_client.models.final_stack.FinalStack(
                        enabled = True, ), ),
        )
        """

    def testClusterConfig(self):
        """Test ClusterConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
