# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.get_block_volume_response import GetBlockVolumeResponse

class TestGetBlockVolumeResponse(unittest.TestCase):
    """GetBlockVolumeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBlockVolumeResponse:
        """Test GetBlockVolumeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBlockVolumeResponse`
        """
        model = GetBlockVolumeResponse()
        if include_optional:
            return GetBlockVolumeResponse(
                id = 56,
                name = '',
                cluster_id = 56,
                backend = 'block',
                access_mode = 'ReadWriteOnce',
                status = 'active',
                pvc_name = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                size_gb = 56,
                storage_class = ''
            )
        else:
            return GetBlockVolumeResponse(
                id = 56,
                name = '',
                cluster_id = 56,
                backend = 'block',
                access_mode = 'ReadWriteOnce',
                status = 'active',
                pvc_name = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                size_gb = 56,
                storage_class = '',
        )
        """

    def testGetBlockVolumeResponse(self):
        """Test GetBlockVolumeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
