# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.volume_access_mode import VolumeAccessMode

class TestVolumeAccessMode(unittest.TestCase):
    """VolumeAccessMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVolumeAccessMode(self):
        """Test VolumeAccessMode"""
        # inst = VolumeAccessMode()

if __name__ == '__main__':
    unittest.main()
