# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.update_cluster_metadata_request import UpdateClusterMetadataRequest

class TestUpdateClusterMetadataRequest(unittest.TestCase):
    """UpdateClusterMetadataRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateClusterMetadataRequest:
        """Test UpdateClusterMetadataRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateClusterMetadataRequest`
        """
        model = UpdateClusterMetadataRequest()
        if include_optional:
            return UpdateClusterMetadataRequest(
                deployment_creation_disabled = True
            )
        else:
            return UpdateClusterMetadataRequest(
                deployment_creation_disabled = True,
        )
        """

    def testUpdateClusterMetadataRequest(self):
        """Test UpdateClusterMetadataRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
