# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.gpu_type_capacity import GpuTypeCapacity

class TestGpuTypeCapacity(unittest.TestCase):
    """GpuTypeCapacity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GpuTypeCapacity:
        """Test GpuTypeCapacity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GpuTypeCapacity`
        """
        model = GpuTypeCapacity()
        if include_optional:
            return GpuTypeCapacity(
                gpu_type = '',
                total_gpus = 56,
                used_gpus = 56
            )
        else:
            return GpuTypeCapacity(
                gpu_type = '',
                total_gpus = 56,
                used_gpus = 56,
        )
        """

    def testGpuTypeCapacity(self):
        """Test GpuTypeCapacity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
