# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_client.models.create_training_deployment_request import CreateTrainingDeploymentRequest

class TestCreateTrainingDeploymentRequest(unittest.TestCase):
    """CreateTrainingDeploymentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateTrainingDeploymentRequest:
        """Test CreateTrainingDeploymentRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateTrainingDeploymentRequest`
        """
        model = CreateTrainingDeploymentRequest()
        if include_optional:
            return CreateTrainingDeploymentRequest(
                name = '',
                image_url = '',
                hardware_instance_id = 56,
                env_vars = {
                    'key' : ''
                    },
                secrets = platform_api_client.models.auth_secret.AuthSecret(
                    username = '', 
                    password = '', )
            )
        else:
            return CreateTrainingDeploymentRequest(
                name = '',
                image_url = '',
                hardware_instance_id = 56,
        )
        """

    def testCreateTrainingDeploymentRequest(self):
        """Test CreateTrainingDeploymentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
