# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.get_filesystem_volume_response import GetFilesystemVolumeResponse

class TestGetFilesystemVolumeResponse(unittest.TestCase):
    """GetFilesystemVolumeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetFilesystemVolumeResponse:
        """Test GetFilesystemVolumeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetFilesystemVolumeResponse`
        """
        model = GetFilesystemVolumeResponse()
        if include_optional:
            return GetFilesystemVolumeResponse(
                id = 56,
                name = '',
                cluster_id = 56,
                backend = 'filesystem',
                access_mode = 'ReadWriteMany',
                status = 'active',
                pvc_name = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                size_gb = 56,
                storage_class = ''
            )
        else:
            return GetFilesystemVolumeResponse(
                id = 56,
                name = '',
                cluster_id = 56,
                backend = 'filesystem',
                access_mode = 'ReadWriteMany',
                status = 'active',
                pvc_name = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                size_gb = 56,
                storage_class = '',
        )
        """

    def testGetFilesystemVolumeResponse(self):
        """Test GetFilesystemVolumeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
