# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.volume_mount import VolumeMount

class TestVolumeMount(unittest.TestCase):
    """VolumeMount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VolumeMount:
        """Test VolumeMount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VolumeMount`
        """
        model = VolumeMount()
        if include_optional:
            return VolumeMount(
                volume_id = 56,
                mount_path = '0',
                read_only = True
            )
        else:
            return VolumeMount(
                volume_id = 56,
                mount_path = '0',
        )
        """

    def testVolumeMount(self):
        """Test VolumeMount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
