# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.metrics_config import MetricsConfig

class TestMetricsConfig(unittest.TestCase):
    """MetricsConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MetricsConfig:
        """Test MetricsConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MetricsConfig`
        """
        model = MetricsConfig()
        if include_optional:
            return MetricsConfig(
                port = 1.0,
                path = '/W(,j>6>eow3jCO&}nl`:&~'
            )
        else:
            return MetricsConfig(
                port = 1.0,
                path = '/W(,j>6>eow3jCO&}nl`:&~',
        )
        """

    def testMetricsConfig(self):
        """Test MetricsConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
