# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.deployment_response import DeploymentResponse

class TestDeploymentResponse(unittest.TestCase):
    """DeploymentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeploymentResponse:
        """Test DeploymentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeploymentResponse`
        """
        model = DeploymentResponse()
        if include_optional:
            return DeploymentResponse(
                creator_email = '',
                cluster_id = 56,
                id = 56,
                name = '',
                endpoint_url = '',
                image_url = '',
                type = 'inference',
                status = 'active',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                hardware_instance_id = 56,
                revision_number = 56,
                user_annotations = {
                    'key' : ''
                    },
                serving_mode = 'aggregated',
                worker_pools = { },
                model = '',
                served_model_name = '',
                min_replicas = 56,
                max_replicas = 56,
                concurrency = 56,
                cooldown_period = 56,
                extra_args = '',
                env_vars = {
                    'key' : ''
                    },
                endpoint_certificate_authority = '',
                endpoint_bearer_token = '',
                enable_logging = True,
                enable_node_model_cache = True,
                backend_protocol = 'HTTP',
                recipe = { },
                cserve_version = '',
                session_affinity = True,
                container_port = 56,
                healthcheck = '',
                command = [
                    ''
                    ],
                command_args = [
                    ''
                    ],
                original_command = '',
                image_pull_secret_credentials = platform_api_python_client.models.image_pull_secret_credentials.ImagePullSecretCredentials(
                    username = '', 
                    password = '', ),
                config_file = platform_api_python_client.models.config_file_mount.ConfigFileMount(
                    filename = '20', 
                    mount_path = '0', 
                    content = '0', ),
                metrics = platform_api_python_client.models.metrics_config.MetricsConfig(
                    port = 1.0, 
                    path = '/W(,j>6>eow3jCO&}nl`:&~', ),
                exposed_port = 56,
                volume_mounts = [
                    platform_api_python_client.models.volume_mount.VolumeMount(
                        volume_id = 56, 
                        mount_path = '0', 
                        read_only = True, )
                    ],
                ssh_public_key = '',
                ssh_password = ''
            )
        else:
            return DeploymentResponse(
                creator_email = '',
                cluster_id = 56,
                id = 56,
                name = '',
                endpoint_url = '',
                type = 'inference',
                status = 'active',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                hardware_instance_id = 56,
                revision_number = 56,
                model = '',
                min_replicas = 56,
                max_replicas = 56,
                recipe = { },
                container_port = 56,
                exposed_port = 56,
        )
        """

    def testDeploymentResponse(self):
        """Test DeploymentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
