# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.get_dynamo_deployment_response import GetDynamoDeploymentResponse

class TestGetDynamoDeploymentResponse(unittest.TestCase):
    """GetDynamoDeploymentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDynamoDeploymentResponse:
        """Test GetDynamoDeploymentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDynamoDeploymentResponse`
        """
        model = GetDynamoDeploymentResponse()
        if include_optional:
            return GetDynamoDeploymentResponse(
                creator_email = '',
                cluster_id = 56,
                id = 56,
                name = '',
                endpoint_url = '',
                image_url = '',
                type = 'inference',
                status = 'active',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                hardware_instance_id = 56,
                revision_number = 56,
                user_annotations = {
                    'key' : ''
                    },
                serving_mode = 'aggregated',
                worker_pools = { },
                model = '',
                served_model_name = '',
                min_replicas = 56,
                max_replicas = 56,
                concurrency = 56,
                cooldown_period = 56,
                extra_args = '',
                env_vars = {
                    'key' : ''
                    },
                endpoint_certificate_authority = '',
                endpoint_bearer_token = '',
                enable_logging = True,
                enable_node_model_cache = True,
                backend_protocol = 'HTTP'
            )
        else:
            return GetDynamoDeploymentResponse(
                creator_email = '',
                cluster_id = 56,
                id = 56,
                name = '',
                endpoint_url = '',
                type = 'inference',
                status = 'active',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                hardware_instance_id = 56,
                revision_number = 56,
                model = '',
                min_replicas = 56,
                max_replicas = 56,
        )
        """

    def testGetDynamoDeploymentResponse(self):
        """Test GetDynamoDeploymentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
