# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.create_volume_request import CreateVolumeRequest

class TestCreateVolumeRequest(unittest.TestCase):
    """CreateVolumeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateVolumeRequest:
        """Test CreateVolumeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateVolumeRequest`
        """
        model = CreateVolumeRequest()
        if include_optional:
            return CreateVolumeRequest(
                name = 'ar1c2v7s6djuy1zmetozkhdomha1b0',
                cluster_id = 56,
                backend = 'object',
                size_gb = 1.0,
                provider = 's3',
                bucket = '012',
                region = '0',
                prefix = '',
                read_only = True,
                volume_attributes = {
                    'key' : ''
                    },
                mount_options = [
                    ''
                    ]
            )
        else:
            return CreateVolumeRequest(
                name = 'ar1c2v7s6djuy1zmetozkhdomha1b0',
                cluster_id = 56,
                backend = 'object',
                bucket = '012',
                region = '0',
        )
        """

    def testCreateVolumeRequest(self):
        """Test CreateVolumeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
