# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.list_hardware_preset_response import ListHardwarePresetResponse

class TestListHardwarePresetResponse(unittest.TestCase):
    """ListHardwarePresetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListHardwarePresetResponse:
        """Test ListHardwarePresetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListHardwarePresetResponse`
        """
        model = ListHardwarePresetResponse()
        if include_optional:
            return ListHardwarePresetResponse(
                results = [
                    platform_api_python_client.models.hardware_preset_response.HardwarePresetResponse(
                        id = 56, 
                        name = '', 
                        gpu_type = '', 
                        num_gpu = 56, 
                        cpu = 56, 
                        memory = 56, 
                        accelerator_resource_key = '', 
                        node_affinity_labels = {
                            'key' : ''
                            }, 
                        accelerator_memory = 56, )
                    ]
            )
        else:
            return ListHardwarePresetResponse(
                results = [
                    platform_api_python_client.models.hardware_preset_response.HardwarePresetResponse(
                        id = 56, 
                        name = '', 
                        gpu_type = '', 
                        num_gpu = 56, 
                        cpu = 56, 
                        memory = 56, 
                        accelerator_resource_key = '', 
                        node_affinity_labels = {
                            'key' : ''
                            }, 
                        accelerator_memory = 56, )
                    ],
        )
        """

    def testListHardwarePresetResponse(self):
        """Test ListHardwarePresetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
