# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.final_stack import FinalStack

class TestFinalStack(unittest.TestCase):
    """FinalStack unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FinalStack:
        """Test FinalStack
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FinalStack`
        """
        model = FinalStack()
        if include_optional:
            return FinalStack(
                enabled = True,
                values = platform_api_python_client.models.final_stack_overrides.FinalStackOverrides()
            )
        else:
            return FinalStack(
        )
        """

    def testFinalStack(self):
        """Test FinalStack"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
