# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.create_job_deployment_request import CreateJobDeploymentRequest

class TestCreateJobDeploymentRequest(unittest.TestCase):
    """CreateJobDeploymentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateJobDeploymentRequest:
        """Test CreateJobDeploymentRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateJobDeploymentRequest`
        """
        model = CreateJobDeploymentRequest()
        if include_optional:
            return CreateJobDeploymentRequest(
                name = 'ar1c2v7s6djuy1zmetozkhdomha1b0',
                cluster_id = 56,
                hardware_instance_id = 56,
                user_annotations = {
                    'key' : ''
                    },
                image_url = '',
                image_pull_secret_credentials = platform_api_python_client.models.image_pull_secret_credentials.ImagePullSecretCredentials(
                    username = '', 
                    password = '', ),
                env_vars = {
                    'key' : ''
                    },
                command = '',
                completions = 56,
                parallelism = 56,
                enable_logging = True
            )
        else:
            return CreateJobDeploymentRequest(
                name = 'ar1c2v7s6djuy1zmetozkhdomha1b0',
                cluster_id = 56,
                hardware_instance_id = 56,
                image_url = '',
        )
        """

    def testCreateJobDeploymentRequest(self):
        """Test CreateJobDeploymentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
