# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.get_job_deployment_response import GetJobDeploymentResponse

class TestGetJobDeploymentResponse(unittest.TestCase):
    """GetJobDeploymentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetJobDeploymentResponse:
        """Test GetJobDeploymentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetJobDeploymentResponse`
        """
        model = GetJobDeploymentResponse()
        if include_optional:
            return GetJobDeploymentResponse(
                creator_email = '',
                cluster_id = 56,
                id = 56,
                name = '',
                endpoint_url = '',
                image_url = '',
                type = 'inference',
                status = 'active',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                hardware_instance_id = 56,
                revision_number = 56,
                user_annotations = {
                    'key' : ''
                    },
                env_vars = {
                    'key' : ''
                    },
                command = [
                    ''
                    ],
                args = [
                    ''
                    ],
                original_command = '',
                completions = 56,
                parallelism = 56,
                backoff_limit = 56,
                active_deadline_seconds = 56,
                image_pull_secret_credentials = platform_api_python_client.models.image_pull_secret_credentials.ImagePullSecretCredentials(
                    username = '', 
                    password = '', ),
                enable_logging = True,
                config_file = platform_api_python_client.models.config_file_mount.ConfigFileMount(
                    filename = '20', 
                    mount_path = '0', 
                    content = '0', )
            )
        else:
            return GetJobDeploymentResponse(
                creator_email = '',
                cluster_id = 56,
                id = 56,
                name = '',
                endpoint_url = '',
                type = 'inference',
                status = 'active',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                hardware_instance_id = 56,
                revision_number = 56,
        )
        """

    def testGetJobDeploymentResponse(self):
        """Test GetJobDeploymentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
