# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.backend_protocol import BackendProtocol

class TestBackendProtocol(unittest.TestCase):
    """BackendProtocol unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBackendProtocol(self):
        """Test BackendProtocol"""
        # inst = BackendProtocol()

if __name__ == '__main__':
    unittest.main()
