# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from platform_api_python_client.models.argo_rollouts import ArgoRollouts
from platform_api_python_client.models.cert_manager import CertManager
from platform_api_python_client.models.external_dns import ExternalDns
from platform_api_python_client.models.final_stack import FinalStack
from platform_api_python_client.models.fluent_bit import FluentBit
from platform_api_python_client.models.gpu_operator import GpuOperator
from platform_api_python_client.models.ingress_nginx import IngressNginx
from platform_api_python_client.models.istio import Istio
from platform_api_python_client.models.keda import Keda
from platform_api_python_client.models.kube_prometheus_stack import KubePrometheusStack
from platform_api_python_client.models.longhorn import Longhorn
from platform_api_python_client.models.metrics_server import MetricsServer
from platform_api_python_client.models.network_operator import NetworkOperator
from platform_api_python_client.models.opentelemetry_collector import OpentelemetryCollector
from platform_api_python_client.models.prometheus_adapter import PrometheusAdapter
from platform_api_python_client.models.spire import Spire
from platform_api_python_client.models.spire_crds import SpireCrds
from platform_api_python_client.models.teleport_kube_agent import TeleportKubeAgent
from typing import Optional, Set
from typing_extensions import Self

class ClusterComponents(BaseModel):
    """
    Per-component ApplicationSet entries — the caller-facing surface.  This is the request-body schema for cluster updates: callers may flip `enabled` and supply per-component `values`, but nothing here is cluster identity. Cluster identity lives in `Shared` and is passed as serialization context when building ApplicationSet elements.  Field declaration order is for code locality only — actual bring-up order is driven by each subclass's `wave` ClassVar (rendered into the child Application's argocd.argoproj.io/sync-wave annotation).
    """ # noqa: E501
    kube_prometheus_stack: Optional[KubePrometheusStack] = None
    istio: Optional[Istio] = None
    cert_manager: Optional[CertManager] = None
    ingress_nginx: Optional[IngressNginx] = None
    spire_crds: Optional[SpireCrds] = None
    spire: Optional[Spire] = None
    external_dns: Optional[ExternalDns] = None
    prometheus_adapter: Optional[PrometheusAdapter] = None
    keda: Optional[Keda] = None
    fluent_bit: Optional[FluentBit] = None
    argo_rollouts: Optional[ArgoRollouts] = None
    network_operator: Optional[NetworkOperator] = None
    opentelemetry_collector: Optional[OpentelemetryCollector] = None
    gpu_operator: Optional[GpuOperator] = None
    longhorn: Optional[Longhorn] = None
    metrics_server: Optional[MetricsServer] = None
    teleport_kube_agent: Optional[TeleportKubeAgent] = None
    final_stack: Optional[FinalStack] = None
    __properties: ClassVar[List[str]] = ["kube_prometheus_stack", "istio", "cert_manager", "ingress_nginx", "spire_crds", "spire", "external_dns", "prometheus_adapter", "keda", "fluent_bit", "argo_rollouts", "network_operator", "opentelemetry_collector", "gpu_operator", "longhorn", "metrics_server", "teleport_kube_agent", "final_stack"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClusterComponents from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of kube_prometheus_stack
        if self.kube_prometheus_stack:
            _dict['kube_prometheus_stack'] = self.kube_prometheus_stack.to_dict()
        # override the default output from pydantic by calling `to_dict()` of istio
        if self.istio:
            _dict['istio'] = self.istio.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cert_manager
        if self.cert_manager:
            _dict['cert_manager'] = self.cert_manager.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ingress_nginx
        if self.ingress_nginx:
            _dict['ingress_nginx'] = self.ingress_nginx.to_dict()
        # override the default output from pydantic by calling `to_dict()` of spire_crds
        if self.spire_crds:
            _dict['spire_crds'] = self.spire_crds.to_dict()
        # override the default output from pydantic by calling `to_dict()` of spire
        if self.spire:
            _dict['spire'] = self.spire.to_dict()
        # override the default output from pydantic by calling `to_dict()` of external_dns
        if self.external_dns:
            _dict['external_dns'] = self.external_dns.to_dict()
        # override the default output from pydantic by calling `to_dict()` of prometheus_adapter
        if self.prometheus_adapter:
            _dict['prometheus_adapter'] = self.prometheus_adapter.to_dict()
        # override the default output from pydantic by calling `to_dict()` of keda
        if self.keda:
            _dict['keda'] = self.keda.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fluent_bit
        if self.fluent_bit:
            _dict['fluent_bit'] = self.fluent_bit.to_dict()
        # override the default output from pydantic by calling `to_dict()` of argo_rollouts
        if self.argo_rollouts:
            _dict['argo_rollouts'] = self.argo_rollouts.to_dict()
        # override the default output from pydantic by calling `to_dict()` of network_operator
        if self.network_operator:
            _dict['network_operator'] = self.network_operator.to_dict()
        # override the default output from pydantic by calling `to_dict()` of opentelemetry_collector
        if self.opentelemetry_collector:
            _dict['opentelemetry_collector'] = self.opentelemetry_collector.to_dict()
        # override the default output from pydantic by calling `to_dict()` of gpu_operator
        if self.gpu_operator:
            _dict['gpu_operator'] = self.gpu_operator.to_dict()
        # override the default output from pydantic by calling `to_dict()` of longhorn
        if self.longhorn:
            _dict['longhorn'] = self.longhorn.to_dict()
        # override the default output from pydantic by calling `to_dict()` of metrics_server
        if self.metrics_server:
            _dict['metrics_server'] = self.metrics_server.to_dict()
        # override the default output from pydantic by calling `to_dict()` of teleport_kube_agent
        if self.teleport_kube_agent:
            _dict['teleport_kube_agent'] = self.teleport_kube_agent.to_dict()
        # override the default output from pydantic by calling `to_dict()` of final_stack
        if self.final_stack:
            _dict['final_stack'] = self.final_stack.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClusterComponents from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "kube_prometheus_stack": KubePrometheusStack.from_dict(obj["kube_prometheus_stack"]) if obj.get("kube_prometheus_stack") is not None else None,
            "istio": Istio.from_dict(obj["istio"]) if obj.get("istio") is not None else None,
            "cert_manager": CertManager.from_dict(obj["cert_manager"]) if obj.get("cert_manager") is not None else None,
            "ingress_nginx": IngressNginx.from_dict(obj["ingress_nginx"]) if obj.get("ingress_nginx") is not None else None,
            "spire_crds": SpireCrds.from_dict(obj["spire_crds"]) if obj.get("spire_crds") is not None else None,
            "spire": Spire.from_dict(obj["spire"]) if obj.get("spire") is not None else None,
            "external_dns": ExternalDns.from_dict(obj["external_dns"]) if obj.get("external_dns") is not None else None,
            "prometheus_adapter": PrometheusAdapter.from_dict(obj["prometheus_adapter"]) if obj.get("prometheus_adapter") is not None else None,
            "keda": Keda.from_dict(obj["keda"]) if obj.get("keda") is not None else None,
            "fluent_bit": FluentBit.from_dict(obj["fluent_bit"]) if obj.get("fluent_bit") is not None else None,
            "argo_rollouts": ArgoRollouts.from_dict(obj["argo_rollouts"]) if obj.get("argo_rollouts") is not None else None,
            "network_operator": NetworkOperator.from_dict(obj["network_operator"]) if obj.get("network_operator") is not None else None,
            "opentelemetry_collector": OpentelemetryCollector.from_dict(obj["opentelemetry_collector"]) if obj.get("opentelemetry_collector") is not None else None,
            "gpu_operator": GpuOperator.from_dict(obj["gpu_operator"]) if obj.get("gpu_operator") is not None else None,
            "longhorn": Longhorn.from_dict(obj["longhorn"]) if obj.get("longhorn") is not None else None,
            "metrics_server": MetricsServer.from_dict(obj["metrics_server"]) if obj.get("metrics_server") is not None else None,
            "teleport_kube_agent": TeleportKubeAgent.from_dict(obj["teleport_kube_agent"]) if obj.get("teleport_kube_agent") is not None else None,
            "final_stack": FinalStack.from_dict(obj["final_stack"]) if obj.get("final_stack") is not None else None
        })
        return _obj


