# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from platform_api_python_client.models.image_pull_secret_credentials import ImagePullSecretCredentials
from platform_api_python_client.models.volume_mount import VolumeMount
from typing import Optional, Set
from typing_extensions import Self

class CreateComputeDeploymentRequest(BaseModel):
    """
    CreateComputeDeploymentRequest
    """ # noqa: E501
    name: Annotated[str, Field(min_length=1, strict=True, max_length=20)]
    cluster_id: StrictInt
    hardware_instance_id: StrictInt
    user_annotations: Optional[Dict[str, StrictStr]] = None
    chart_revision: Optional[StrictStr] = None
    image_url: StrictStr
    image_pull_secret_credentials: Optional[ImagePullSecretCredentials] = None
    ssh_public_key: StrictStr
    enable_logging: Optional[StrictBool] = False
    volume_mounts: Optional[List[VolumeMount]] = None
    __properties: ClassVar[List[str]] = ["name", "cluster_id", "hardware_instance_id", "user_annotations", "chart_revision", "image_url", "image_pull_secret_credentials", "ssh_public_key", "enable_logging", "volume_mounts"]

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-z][a-z0-9-]*$", value):
            raise ValueError(r"must validate the regular expression /^[a-z][a-z0-9-]*$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateComputeDeploymentRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of image_pull_secret_credentials
        if self.image_pull_secret_credentials:
            _dict['image_pull_secret_credentials'] = self.image_pull_secret_credentials.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in volume_mounts (list)
        _items = []
        if self.volume_mounts:
            for _item_volume_mounts in self.volume_mounts:
                if _item_volume_mounts:
                    _items.append(_item_volume_mounts.to_dict())
            _dict['volume_mounts'] = _items
        # set to None if user_annotations (nullable) is None
        # and model_fields_set contains the field
        if self.user_annotations is None and "user_annotations" in self.model_fields_set:
            _dict['user_annotations'] = None

        # set to None if image_pull_secret_credentials (nullable) is None
        # and model_fields_set contains the field
        if self.image_pull_secret_credentials is None and "image_pull_secret_credentials" in self.model_fields_set:
            _dict['image_pull_secret_credentials'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateComputeDeploymentRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "cluster_id": obj.get("cluster_id"),
            "hardware_instance_id": obj.get("hardware_instance_id"),
            "user_annotations": obj.get("user_annotations"),
            "chart_revision": obj.get("chart_revision"),
            "image_url": obj.get("image_url"),
            "image_pull_secret_credentials": ImagePullSecretCredentials.from_dict(obj["image_pull_secret_credentials"]) if obj.get("image_pull_secret_credentials") is not None else None,
            "ssh_public_key": obj.get("ssh_public_key"),
            "enable_logging": obj.get("enable_logging") if obj.get("enable_logging") is not None else False,
            "volume_mounts": [VolumeMount.from_dict(_item) for _item in obj["volume_mounts"]] if obj.get("volume_mounts") is not None else None
        })
        return _obj


