# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from platform_api_python_client.models.backend_protocol import BackendProtocol
from platform_api_python_client.models.image_pull_secret_credentials import ImagePullSecretCredentials
from typing import Optional, Set
from typing_extensions import Self

class CreateDynamoDeploymentRequest(BaseModel):
    """
    Create a NVIDIA Dynamo (DynamoGraphDeployment) inference deployment.  Aggregated + KV-router pattern with a vLLM backend. The Frontend pod enables KV-aware routing across worker replicas.
    """ # noqa: E501
    max_surge: Optional[StrictInt] = None
    max_unavailable: Optional[StrictInt] = None
    name: Annotated[str, Field(min_length=1, strict=True, max_length=20)]
    cluster_id: StrictInt
    hardware_instance_id: StrictInt
    user_annotations: Optional[Dict[str, StrictStr]] = None
    chart_revision: Optional[StrictStr] = None
    image_url: StrictStr
    image_pull_secret_credentials: Optional[ImagePullSecretCredentials] = None
    model: StrictStr
    served_model_name: Optional[StrictStr] = None
    container_port: Optional[Annotated[int, Field(le=65535, strict=True, ge=1024)]] = Field(default=8000, description="Internal Dynamo Frontend listener port for the non-root runtime. The public endpoint remains on HTTPS; port 8788 is unavailable when backend_protocol is GRPC.")
    initial_replicas: Optional[StrictInt] = 1
    gpus_per_worker: Optional[StrictInt] = 1
    extra_args: Optional[StrictStr] = None
    hf_token: Optional[StrictStr] = None
    hf_token_secret_name: Optional[StrictStr] = None
    env_vars: Optional[Dict[str, StrictStr]] = None
    endpoint_bearer_token: Optional[StrictStr] = None
    endpoint_certificate_authority: Optional[StrictStr] = None
    enable_logging: Optional[StrictBool] = True
    enable_node_model_cache: Optional[StrictBool] = False
    backend_protocol: Optional[BackendProtocol] = None
    __properties: ClassVar[List[str]] = ["max_surge", "max_unavailable", "name", "cluster_id", "hardware_instance_id", "user_annotations", "chart_revision", "image_url", "image_pull_secret_credentials", "model", "served_model_name", "container_port", "initial_replicas", "gpus_per_worker", "extra_args", "hf_token", "hf_token_secret_name", "env_vars", "endpoint_bearer_token", "endpoint_certificate_authority", "enable_logging", "enable_node_model_cache", "backend_protocol"]

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-z][a-z0-9-]*$", value):
            raise ValueError(r"must validate the regular expression /^[a-z][a-z0-9-]*$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateDynamoDeploymentRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of image_pull_secret_credentials
        if self.image_pull_secret_credentials:
            _dict['image_pull_secret_credentials'] = self.image_pull_secret_credentials.to_dict()
        # set to None if max_surge (nullable) is None
        # and model_fields_set contains the field
        if self.max_surge is None and "max_surge" in self.model_fields_set:
            _dict['max_surge'] = None

        # set to None if max_unavailable (nullable) is None
        # and model_fields_set contains the field
        if self.max_unavailable is None and "max_unavailable" in self.model_fields_set:
            _dict['max_unavailable'] = None

        # set to None if user_annotations (nullable) is None
        # and model_fields_set contains the field
        if self.user_annotations is None and "user_annotations" in self.model_fields_set:
            _dict['user_annotations'] = None

        # set to None if image_pull_secret_credentials (nullable) is None
        # and model_fields_set contains the field
        if self.image_pull_secret_credentials is None and "image_pull_secret_credentials" in self.model_fields_set:
            _dict['image_pull_secret_credentials'] = None

        # set to None if served_model_name (nullable) is None
        # and model_fields_set contains the field
        if self.served_model_name is None and "served_model_name" in self.model_fields_set:
            _dict['served_model_name'] = None

        # set to None if extra_args (nullable) is None
        # and model_fields_set contains the field
        if self.extra_args is None and "extra_args" in self.model_fields_set:
            _dict['extra_args'] = None

        # set to None if hf_token (nullable) is None
        # and model_fields_set contains the field
        if self.hf_token is None and "hf_token" in self.model_fields_set:
            _dict['hf_token'] = None

        # set to None if hf_token_secret_name (nullable) is None
        # and model_fields_set contains the field
        if self.hf_token_secret_name is None and "hf_token_secret_name" in self.model_fields_set:
            _dict['hf_token_secret_name'] = None

        # set to None if endpoint_bearer_token (nullable) is None
        # and model_fields_set contains the field
        if self.endpoint_bearer_token is None and "endpoint_bearer_token" in self.model_fields_set:
            _dict['endpoint_bearer_token'] = None

        # set to None if endpoint_certificate_authority (nullable) is None
        # and model_fields_set contains the field
        if self.endpoint_certificate_authority is None and "endpoint_certificate_authority" in self.model_fields_set:
            _dict['endpoint_certificate_authority'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateDynamoDeploymentRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "max_surge": obj.get("max_surge"),
            "max_unavailable": obj.get("max_unavailable"),
            "name": obj.get("name"),
            "cluster_id": obj.get("cluster_id"),
            "hardware_instance_id": obj.get("hardware_instance_id"),
            "user_annotations": obj.get("user_annotations"),
            "chart_revision": obj.get("chart_revision"),
            "image_url": obj.get("image_url"),
            "image_pull_secret_credentials": ImagePullSecretCredentials.from_dict(obj["image_pull_secret_credentials"]) if obj.get("image_pull_secret_credentials") is not None else None,
            "model": obj.get("model"),
            "served_model_name": obj.get("served_model_name"),
            "container_port": obj.get("container_port") if obj.get("container_port") is not None else 8000,
            "initial_replicas": obj.get("initial_replicas") if obj.get("initial_replicas") is not None else 1,
            "gpus_per_worker": obj.get("gpus_per_worker") if obj.get("gpus_per_worker") is not None else 1,
            "extra_args": obj.get("extra_args"),
            "hf_token": obj.get("hf_token"),
            "hf_token_secret_name": obj.get("hf_token_secret_name"),
            "env_vars": obj.get("env_vars"),
            "endpoint_bearer_token": obj.get("endpoint_bearer_token"),
            "endpoint_certificate_authority": obj.get("endpoint_certificate_authority"),
            "enable_logging": obj.get("enable_logging") if obj.get("enable_logging") is not None else True,
            "enable_node_model_cache": obj.get("enable_node_model_cache") if obj.get("enable_node_model_cache") is not None else False,
            "backend_protocol": obj.get("backend_protocol")
        })
        return _obj


