# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from platform_api_python_client.models.backend_protocol import BackendProtocol
from platform_api_python_client.models.dynamo_communications_input import DynamoCommunicationsInput
from platform_api_python_client.models.dynamo_serving_mode import DynamoServingMode
from platform_api_python_client.models.dynamo_worker_pools import DynamoWorkerPools
from platform_api_python_client.models.volume_mount import VolumeMount
from typing import Optional, Set
from typing_extensions import Self

class CreateDynamoDeploymentRequest(BaseModel):
    """
    Create a Dynamo deployment.  Hardware and scaling live under ``worker_pools``: aggregated mode uses exactly ``worker_pools.worker``; disaggregated mode uses exactly ``worker_pools.prefill`` and ``worker_pools.decode`` (fixed-size until per-role autoscaling ships). The top-level ``hardware_instance_id`` / ``min_replicas`` / ``max_replicas`` / ``concurrency`` / ``cooldown_period`` fields are the deprecated aggregated-only spelling; they stay accepted and may accompany ``worker_pools`` when they agree with it. ``parse_dynamo_topology`` owns every topology rule for both spellings.
    """ # noqa: E501
    max_surge: Optional[StrictInt] = None
    max_unavailable: Optional[StrictInt] = None
    name: Annotated[str, Field(min_length=1, strict=True, max_length=20)]
    cluster_id: StrictInt
    hardware_instance_id: Optional[StrictInt] = None
    user_annotations: Optional[Dict[str, StrictStr]] = None
    chart_revision: Optional[StrictStr] = None
    volume_mounts: Optional[Annotated[List[VolumeMount], Field(max_length=10)]] = None
    priority: Optional[Annotated[str, Field(strict=True, max_length=253)]] = None
    serving_mode: Optional[DynamoServingMode] = None
    worker_pools: Optional[DynamoWorkerPools] = None
    communications: Optional[DynamoCommunicationsInput] = None
    model: StrictStr
    served_model_name: Optional[StrictStr] = None
    runtime_version: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Dynamo runtime image tag (for example 1.4.0). Defaults to the platform's current release; GET /prebuilt-images?type=dynamo lists the versions the platform has validated, but any tag may be requested. require_gpu_direct_rdma needs an EFA-capable image. Changing it restarts every component of a running deployment.")
    min_replicas: Optional[StrictInt] = None
    max_replicas: Optional[StrictInt] = None
    concurrency: Optional[StrictInt] = None
    cooldown_period: Optional[StrictInt] = None
    extra_args: Optional[StrictStr] = None
    hf_token: Optional[StrictStr] = None
    env_vars: Optional[Dict[str, StrictStr]] = None
    endpoint_bearer_token: Optional[StrictStr] = None
    endpoint_certificate_authority: Optional[StrictStr] = None
    enable_logging: Optional[StrictBool] = True
    enable_node_model_cache: Optional[StrictBool] = False
    backend_protocol: Optional[BackendProtocol] = None
    __properties: ClassVar[List[str]] = ["max_surge", "max_unavailable", "name", "cluster_id", "hardware_instance_id", "user_annotations", "chart_revision", "volume_mounts", "priority", "serving_mode", "worker_pools", "communications", "model", "served_model_name", "runtime_version", "min_replicas", "max_replicas", "concurrency", "cooldown_period", "extra_args", "hf_token", "env_vars", "endpoint_bearer_token", "endpoint_certificate_authority", "enable_logging", "enable_node_model_cache", "backend_protocol"]

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-z][a-z0-9-]*$", value):
            raise ValueError(r"must validate the regular expression /^[a-z][a-z0-9-]*$/")
        return value

    @field_validator('runtime_version')
    def runtime_version_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Za-z0-9_][A-Za-z0-9._-]{0,127}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9_][A-Za-z0-9._-]{0,127}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateDynamoDeploymentRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in volume_mounts (list)
        _items = []
        if self.volume_mounts:
            for _item_volume_mounts in self.volume_mounts:
                if _item_volume_mounts:
                    _items.append(_item_volume_mounts.to_dict())
            _dict['volume_mounts'] = _items
        # override the default output from pydantic by calling `to_dict()` of worker_pools
        if self.worker_pools:
            _dict['worker_pools'] = self.worker_pools.to_dict()
        # override the default output from pydantic by calling `to_dict()` of communications
        if self.communications:
            _dict['communications'] = self.communications.to_dict()
        # set to None if max_surge (nullable) is None
        # and model_fields_set contains the field
        if self.max_surge is None and "max_surge" in self.model_fields_set:
            _dict['max_surge'] = None

        # set to None if max_unavailable (nullable) is None
        # and model_fields_set contains the field
        if self.max_unavailable is None and "max_unavailable" in self.model_fields_set:
            _dict['max_unavailable'] = None

        # set to None if hardware_instance_id (nullable) is None
        # and model_fields_set contains the field
        if self.hardware_instance_id is None and "hardware_instance_id" in self.model_fields_set:
            _dict['hardware_instance_id'] = None

        # set to None if user_annotations (nullable) is None
        # and model_fields_set contains the field
        if self.user_annotations is None and "user_annotations" in self.model_fields_set:
            _dict['user_annotations'] = None

        # set to None if priority (nullable) is None
        # and model_fields_set contains the field
        if self.priority is None and "priority" in self.model_fields_set:
            _dict['priority'] = None

        # set to None if worker_pools (nullable) is None
        # and model_fields_set contains the field
        if self.worker_pools is None and "worker_pools" in self.model_fields_set:
            _dict['worker_pools'] = None

        # set to None if communications (nullable) is None
        # and model_fields_set contains the field
        if self.communications is None and "communications" in self.model_fields_set:
            _dict['communications'] = None

        # set to None if served_model_name (nullable) is None
        # and model_fields_set contains the field
        if self.served_model_name is None and "served_model_name" in self.model_fields_set:
            _dict['served_model_name'] = None

        # set to None if min_replicas (nullable) is None
        # and model_fields_set contains the field
        if self.min_replicas is None and "min_replicas" in self.model_fields_set:
            _dict['min_replicas'] = None

        # set to None if max_replicas (nullable) is None
        # and model_fields_set contains the field
        if self.max_replicas is None and "max_replicas" in self.model_fields_set:
            _dict['max_replicas'] = None

        # set to None if concurrency (nullable) is None
        # and model_fields_set contains the field
        if self.concurrency is None and "concurrency" in self.model_fields_set:
            _dict['concurrency'] = None

        # set to None if cooldown_period (nullable) is None
        # and model_fields_set contains the field
        if self.cooldown_period is None and "cooldown_period" in self.model_fields_set:
            _dict['cooldown_period'] = None

        # set to None if extra_args (nullable) is None
        # and model_fields_set contains the field
        if self.extra_args is None and "extra_args" in self.model_fields_set:
            _dict['extra_args'] = None

        # set to None if hf_token (nullable) is None
        # and model_fields_set contains the field
        if self.hf_token is None and "hf_token" in self.model_fields_set:
            _dict['hf_token'] = None

        # set to None if endpoint_bearer_token (nullable) is None
        # and model_fields_set contains the field
        if self.endpoint_bearer_token is None and "endpoint_bearer_token" in self.model_fields_set:
            _dict['endpoint_bearer_token'] = None

        # set to None if endpoint_certificate_authority (nullable) is None
        # and model_fields_set contains the field
        if self.endpoint_certificate_authority is None and "endpoint_certificate_authority" in self.model_fields_set:
            _dict['endpoint_certificate_authority'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateDynamoDeploymentRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "max_surge": obj.get("max_surge"),
            "max_unavailable": obj.get("max_unavailable"),
            "name": obj.get("name"),
            "cluster_id": obj.get("cluster_id"),
            "hardware_instance_id": obj.get("hardware_instance_id"),
            "user_annotations": obj.get("user_annotations"),
            "chart_revision": obj.get("chart_revision"),
            "volume_mounts": [VolumeMount.from_dict(_item) for _item in obj["volume_mounts"]] if obj.get("volume_mounts") is not None else None,
            "priority": obj.get("priority"),
            "serving_mode": obj.get("serving_mode"),
            "worker_pools": DynamoWorkerPools.from_dict(obj["worker_pools"]) if obj.get("worker_pools") is not None else None,
            "communications": DynamoCommunicationsInput.from_dict(obj["communications"]) if obj.get("communications") is not None else None,
            "model": obj.get("model"),
            "served_model_name": obj.get("served_model_name"),
            "runtime_version": obj.get("runtime_version"),
            "min_replicas": obj.get("min_replicas"),
            "max_replicas": obj.get("max_replicas"),
            "concurrency": obj.get("concurrency"),
            "cooldown_period": obj.get("cooldown_period"),
            "extra_args": obj.get("extra_args"),
            "hf_token": obj.get("hf_token"),
            "env_vars": obj.get("env_vars"),
            "endpoint_bearer_token": obj.get("endpoint_bearer_token"),
            "endpoint_certificate_authority": obj.get("endpoint_certificate_authority"),
            "enable_logging": obj.get("enable_logging") if obj.get("enable_logging") is not None else True,
            "enable_node_model_cache": obj.get("enable_node_model_cache") if obj.get("enable_node_model_cache") is not None else False,
            "backend_protocol": obj.get("backend_protocol")
        })
        return _obj


