# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from platform_api_python_client.models.backend_protocol import BackendProtocol
from platform_api_python_client.models.deployment_status import DeploymentStatus
from platform_api_python_client.models.deployment_type import DeploymentType
from typing import Optional, Set
from typing_extensions import Self

class GetDynamoDeploymentResponse(BaseModel):
    """
    GetDynamoDeploymentResponse
    """ # noqa: E501
    creator_email: StrictStr
    cluster_id: StrictInt
    id: StrictInt
    name: StrictStr
    endpoint_url: StrictStr
    image_url: Optional[StrictStr] = None
    type: DeploymentType
    status: DeploymentStatus
    created_at: datetime
    hardware_instance_id: StrictInt
    revision_number: StrictInt
    user_annotations: Optional[Dict[str, StrictStr]] = None
    model: StrictStr
    served_model_name: Optional[StrictStr] = None
    min_replicas: StrictInt
    max_replicas: StrictInt
    concurrency: Optional[StrictInt] = None
    cooldown_period: Optional[StrictInt] = None
    extra_args: Optional[StrictStr] = None
    env_vars: Optional[Dict[str, StrictStr]] = None
    endpoint_certificate_authority: Optional[StrictStr] = None
    endpoint_bearer_token: Optional[StrictStr] = None
    enable_logging: Optional[StrictBool] = True
    enable_node_model_cache: Optional[StrictBool] = False
    backend_protocol: Optional[BackendProtocol] = None
    __properties: ClassVar[List[str]] = ["creator_email", "cluster_id", "id", "name", "endpoint_url", "image_url", "type", "status", "created_at", "hardware_instance_id", "revision_number", "user_annotations", "model", "served_model_name", "min_replicas", "max_replicas", "concurrency", "cooldown_period", "extra_args", "env_vars", "endpoint_certificate_authority", "endpoint_bearer_token", "enable_logging", "enable_node_model_cache", "backend_protocol"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetDynamoDeploymentResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if image_url (nullable) is None
        # and model_fields_set contains the field
        if self.image_url is None and "image_url" in self.model_fields_set:
            _dict['image_url'] = None

        # set to None if user_annotations (nullable) is None
        # and model_fields_set contains the field
        if self.user_annotations is None and "user_annotations" in self.model_fields_set:
            _dict['user_annotations'] = None

        # set to None if served_model_name (nullable) is None
        # and model_fields_set contains the field
        if self.served_model_name is None and "served_model_name" in self.model_fields_set:
            _dict['served_model_name'] = None

        # set to None if concurrency (nullable) is None
        # and model_fields_set contains the field
        if self.concurrency is None and "concurrency" in self.model_fields_set:
            _dict['concurrency'] = None

        # set to None if cooldown_period (nullable) is None
        # and model_fields_set contains the field
        if self.cooldown_period is None and "cooldown_period" in self.model_fields_set:
            _dict['cooldown_period'] = None

        # set to None if extra_args (nullable) is None
        # and model_fields_set contains the field
        if self.extra_args is None and "extra_args" in self.model_fields_set:
            _dict['extra_args'] = None

        # set to None if endpoint_certificate_authority (nullable) is None
        # and model_fields_set contains the field
        if self.endpoint_certificate_authority is None and "endpoint_certificate_authority" in self.model_fields_set:
            _dict['endpoint_certificate_authority'] = None

        # set to None if endpoint_bearer_token (nullable) is None
        # and model_fields_set contains the field
        if self.endpoint_bearer_token is None and "endpoint_bearer_token" in self.model_fields_set:
            _dict['endpoint_bearer_token'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetDynamoDeploymentResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "creator_email": obj.get("creator_email"),
            "cluster_id": obj.get("cluster_id"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "endpoint_url": obj.get("endpoint_url"),
            "image_url": obj.get("image_url"),
            "type": obj.get("type"),
            "status": obj.get("status"),
            "created_at": obj.get("created_at"),
            "hardware_instance_id": obj.get("hardware_instance_id"),
            "revision_number": obj.get("revision_number"),
            "user_annotations": obj.get("user_annotations"),
            "model": obj.get("model"),
            "served_model_name": obj.get("served_model_name"),
            "min_replicas": obj.get("min_replicas"),
            "max_replicas": obj.get("max_replicas"),
            "concurrency": obj.get("concurrency"),
            "cooldown_period": obj.get("cooldown_period"),
            "extra_args": obj.get("extra_args"),
            "env_vars": obj.get("env_vars"),
            "endpoint_certificate_authority": obj.get("endpoint_certificate_authority"),
            "endpoint_bearer_token": obj.get("endpoint_bearer_token"),
            "enable_logging": obj.get("enable_logging") if obj.get("enable_logging") is not None else True,
            "enable_node_model_cache": obj.get("enable_node_model_cache") if obj.get("enable_node_model_cache") is not None else False,
            "backend_protocol": obj.get("backend_protocol")
        })
        return _obj


