# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from platform_api_python_client.models.object_storage_provider import ObjectStorageProvider
from platform_api_python_client.models.volume_access_mode import VolumeAccessMode
from platform_api_python_client.models.volume_status import VolumeStatus
from typing import Optional, Set
from typing_extensions import Self

class GetObjectVolumeResponse(BaseModel):
    """
    GetObjectVolumeResponse
    """ # noqa: E501
    id: StrictInt
    name: StrictStr
    cluster_id: StrictInt
    backend: StrictStr
    access_mode: VolumeAccessMode
    status: VolumeStatus
    pvc_name: StrictStr
    created_at: datetime
    provider: ObjectStorageProvider
    bucket: StrictStr
    region: StrictStr
    prefix: Optional[StrictStr] = None
    read_only: StrictBool
    volume_attributes: Optional[Dict[str, StrictStr]] = None
    mount_options: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["id", "name", "cluster_id", "backend", "access_mode", "status", "pvc_name", "created_at", "provider", "bucket", "region", "prefix", "read_only", "volume_attributes", "mount_options"]

    @field_validator('backend')
    def backend_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['object']):
            raise ValueError("must be one of enum values ('object')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetObjectVolumeResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if prefix (nullable) is None
        # and model_fields_set contains the field
        if self.prefix is None and "prefix" in self.model_fields_set:
            _dict['prefix'] = None

        # set to None if volume_attributes (nullable) is None
        # and model_fields_set contains the field
        if self.volume_attributes is None and "volume_attributes" in self.model_fields_set:
            _dict['volume_attributes'] = None

        # set to None if mount_options (nullable) is None
        # and model_fields_set contains the field
        if self.mount_options is None and "mount_options" in self.model_fields_set:
            _dict['mount_options'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetObjectVolumeResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "cluster_id": obj.get("cluster_id"),
            "backend": obj.get("backend"),
            "access_mode": obj.get("access_mode"),
            "status": obj.get("status"),
            "pvc_name": obj.get("pvc_name"),
            "created_at": obj.get("created_at"),
            "provider": obj.get("provider"),
            "bucket": obj.get("bucket"),
            "region": obj.get("region"),
            "prefix": obj.get("prefix"),
            "read_only": obj.get("read_only"),
            "volume_attributes": obj.get("volume_attributes"),
            "mount_options": obj.get("mount_options")
        })
        return _obj


